<?php

/**
 * @vendor      Revton
 * @theme       Revton_Amr
 * @author      Amr Osama <amrosama5@gmail.com>
 */

// phpcs:disable Generic.Files.LineLength.TooLong
?>
<div class="menu-toggle-wrapper">
    <button class="action menu-toggle"
        type="button"
        aria-label="Toggle Menu"
        aria-controls="navigation"
        aria-expanded="false">
        <span class="open-menu-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M0.5 3.5H23.5V4.5H0.5V3.5Z" fill="#313231" />
                <path fill-rule="evenodd" clip-rule="evenodd" d="M0.5 11.5H21.5V12.5H0.5V11.5Z" fill="#313231" />
                <path fill-rule="evenodd" clip-rule="evenodd" d="M0.5 19.5H14.5V20.5H0.5V19.5Z" fill="#313231" />
            </svg>
        </span>
        <span class="close-menu-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M11.2929 12L3.14648 3.85353L3.85359 3.14642L12 11.2929L20.1465 3.14642L20.8536 3.85353L12.7071 12L20.8536 20.1464L20.1465 20.8535L12 12.7071L3.85359 20.8535L3.14648 20.1464L11.2929 12Z" fill="#313231" />
            </svg>
        </span>
    </button>
</div>