<?php

/**
 * @vendor    Revton
 * @theme     Revton_Amr
 * @author    Amr Osama <amrosama5@gmail.com>
 */

use Magento\Framework\Escaper;
use Snowdog\Menu\Block\NodeType\CustomUrl;

/** @var CustomUrl $block */
/** @var Escaper $escaper */

$attributes = [];
$class = $block->getMenuClass();
$content = $block->getContent();

if ($block->getIsViewAllLink()) {
    $title = __('View All');
    $classLink = $class . '__inner-link';
} else {
    $classLink = $block->getIsRoot() ? $class . '__link' : $class . '__inner-link';
    $title = $block->getTitle();
    if ($block->getId()) {
        $attributes[] = 'data-menu="menu-' . $block->getId() . '"';
    }
}
$attributes[] = 'class="' . $classLink . ' link "';

if ($block->getTarget()) {
    $attributes[] = 'target="_blank" rel="noopener"';
}
$allAttributes = implode(' ', $attributes);
?>
<?php if ($content): ?>
    <a href="<?= $escaper->escapeUrl($content); ?>"
        <?= /* @noEscape */ $allAttributes; ?>>
        <?= $escaper->escapeHtml($title); ?>
    </a>
<?php else: ?>
    <span <?= /* @noEscape */ $allAttributes ?>
        tabindex="0">
        <?= $escaper->escapeHtml($title); ?>
    </span>
<?php endif; ?>